// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_64SjrQDqWwBNCm4IbBLR-QToMVMjvjg',
    appId: '1:60718038713:web:55c5f93876accc5e9f2568',
    messagingSenderId: '60718038713',
    projectId: 'notification-f0089',
    authDomain: 'notification-f0089.firebaseapp.com',
    storageBucket: 'notification-f0089.appspot.com',
    measurementId: 'G-WGMS00Y8E2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqo-d0sqktxgT_aZZj1YsuohcZ0fcdF_8',
    appId: '1:60718038713:ios:8f2a6263661ec3fa9f2568',
    messagingSenderId: '60718038713',
    projectId: 'notification-f0089',
    storageBucket: 'notification-f0089.appspot.com',
    iosBundleId: 'com.example.pharmachyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_64SjrQDqWwBNCm4IbBLR-QToMVMjvjg',
    appId: '1:60718038713:web:6302c8ffc5a0a0109f2568',
    messagingSenderId: '60718038713',
    projectId: 'notification-f0089',
    authDomain: 'notification-f0089.firebaseapp.com',
    storageBucket: 'notification-f0089.appspot.com',
    measurementId: 'G-W6E3YETHMY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqo-d0sqktxgT_aZZj1YsuohcZ0fcdF_8',
    appId: '1:60718038713:ios:8f2a6263661ec3fa9f2568',
    messagingSenderId: '60718038713',
    projectId: 'notification-f0089',
    storageBucket: 'notification-f0089.appspot.com',
    iosBundleId: 'com.example.pharmachyApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGVX7oEaxnhPm-t51_GWPkAmDEhCvvkLM',
    appId: '1:60718038713:android:d2d9ce08c316fe349f2568',
    messagingSenderId: '60718038713',
    projectId: 'notification-f0089',
    storageBucket: 'notification-f0089.appspot.com',
  );

}